version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3000"
  product-service:
    build: ./product-service
    ports:
      - "3002:3000"
  cart-service:
    build: ./cart-service
    ports:
      - "3003:3000"
  order-service:
    build: ./order-service
    ports:
      - "3004:3000"
  payment-service:
    build: ./payment-service
    ports:
      - "3005:3000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
